application: rock-dragon-92018
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /.*
  script: templates.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest